### ISSUE TITLE
App is not working anymore on Android 12 since last update

### ISSUE THREAD

**Issue by Raptor039** [devgianlu/Aria2App#236]
Hi and thanks for this project. I'm using Aria2app on Android for years and it has always worked flawlessly.

However, since the last update (v5.9.10), Aria2app just opens up and hangs on the logo page until crash.

I'm on Android 12 running on a Pixel 6 Pro phone.

Let me know if I can give you more information about this bug and how to do that.

**Comment by guojian0624** [comment]
Me too, Pixel5a Android 12

**Comment by hdatma** [comment]
Same here, on Samsung.

**Comment by devgianlu** [comment]
Please check the latest update on the play store.

**Comment by Raptor039** [comment]
> Please check the latest update on the play store.

Yes thanks ! It works again like a charm 👍🙂

**Comment by hdatma** [comment]
Still broken. I think the problem is the local configuration. The new app crashes with the old config, refuses importing aria2app-exported-global.conf, and the creation of a new profile using the instructions makes it impossible to use the smartphone as both client and server. I think the welcome page should offer a default configuration when selecting Mobile as connectivity condition.

**Comment by devgianlu** [comment]
I've pushed another updated on the Play Store, this issue effects only users with the NotificationService enabled.

**Comment by Raptor039** [comment]
> I've pushed another updated on the Play Store, this issue effects only users with the NotificationService enabled.

Hi @devgianlu, it finally works well with latestest update 5.9.12. Thanks for your works.

Issue can be solved for me.
