### ISSUE TITLE
Feature Request: Shutdown buttons on the sliding menu and notification?

### ISSUE THREAD

**Issue by Pentaphon** [devgianlu/Aria2App#55]
I'd like a way to quickly shut down the app when I don't need it anymore. Can you add a shutdown button to the sliding menu under "support" and maybe a shutdown button on the notification as well? Sometimes I just need the app to run for a short while and don't need it running for very long.

**Comment by devgianlu** [comment]
I've added a button to stop the service on the notification. The new release will be out in a few minutes.

**Comment by Pentaphon** [comment]
Thanks!

**Comment by SumatraPeter** [comment]
@devgianlu: Thanks for adding this option. However it seems that as long as the notification service (with the inverted A icon) is enabled under the app's Preferences, while that can indeed be shut down, the main downloader service (with the a<sup>2</sup> icon) still remains running even if the app is terminated. If the notification service is disabled however, then terminating the app seems to successfully stop the downloader service as well, because then the a<sup>2</sup> icon and associated notification disappear.

So my request would be to add a shutdown button to the downloader service notification as well, and better still to have it shut down automatically when the app is terminated, irrespective of whether the notification service is enabled or not.

**Comment by devgianlu** [comment]
I'll have a look, it's definitely an unwanted behavior.

**Comment by devgianlu** [comment]
@SumatraPeter Maybe I did not fully understand, but the notification service has a dedicated shutdown button. The reason why it doesn't shut down with the downloader service is that you might have some remote server you want to get notifications from. 

If you don't see the notification service shutdown button, that's a different problem. Did I understand correctly?

**Comment by SumatraPeter** [comment]
No, you seem to have misunderstood. The notification service can be shut down fine; it is the downloader service ("Service for aria2" - see screenshot below) that keeps running for some reason even if I terminate the app (that is, I continue to see a notification for it with the a<sup>2</sup> icon indicating that it is still running). If I disable the notification service from the app's settings however, when I terminate the app the downloader service also terminates and its notification disappears.

So my request is to add a shutdown button to the downloader service's notification also so that we can manually terminate it, and/or make the downloader service terminate properly when the app is closed, even if the notification service is enabled under settings. I hope that explains it...

![Screenshot_2021-02-25](https://user-images.githubusercontent.com/15380332/109084593-10dc3500-772e-11eb-8e86-432c3ef6aeab.jpg)

**Comment by devgianlu** [comment]
Ok now I get it. There was an issue with now the notification was created that I fixed with the last few commits on aria2lib. As a workaround until the next version is out, you can disable "Show Performance" in the InApp-Downloader settings.

**Comment by SumatraPeter** [comment]
That's good news. However try as I might I can't seem to find the "Show Performance" option - where is it supposed to be in v5.9.5 exactly?
