### ISSUE TITLE
Is the latest aria2 release (1.35) working for you?

### ISSUE THREAD

**Issue by opusforlife2** [devgianlu/Aria2App#81]
It wasn't starting for me, and the log showed an error. I had to revert to 1.34.

**Comment by DazzyWalkman** [comment]
A big no for my ARMv7 phone.

**Comment by devgianlu** [comment]
Could you post an screenshot of the error? (It works on my device) So that I know how the error looks like.

**Comment by DazzyWalkman** [comment]
When bin file download completed, then aria2app tried to connect to in-app-downloader,  a cross mark indicating in-app aria2c service is unreachable. Period.
I attach a log screeny including related lines here. I will send you a more complete, filtered log later when I have time.
![IMG_20191007_205351](https://user-images.githubusercontent.com/20811819/66314145-2ccb1500-e946-11e9-9bb6-67697d16a89e.png)

**Comment by opusforlife2** [comment]
My error message is simpler. I'll just type it because it's small enough.

INFO: CANNOT LINK EXECUTABLE "/data/user/0/com.gianlu.aria2app/files/env/aria2c": cannot locate symbol "fread_unlocked" referenced by "/data/data/com.gianlu.aria2app/files/env/aria2c"...

INFO: Terminated with exit code 134.

**Comment by DazzyWalkman** [comment]
Mine is as simple as yours, but since I reply from my phone, I just spared some writing or copy/paste :-p
One thing is missing, our phone models. I think this will help on this issue. So I prefer to include this bit later.
I read commits of aria2c source, and find this one:
https://github.com/aria2/aria2/commit/9f5758570a51feca6a468aea6a29377566addd87
Time to say goodbye to legacy phone without 64 bit support or stick with 1.34.
I am quite confident it will compile reverting this change, but still no go for future aria2c versions.

**Comment by devgianlu** [comment]
I've successfully build some executables (working on x86 too!!), but they are enormous: 60+MB. Will work on reducing the file size.

**Comment by devgianlu** [comment]
Fixed with version `5.4.0`. You can now re-download a compatible binary. 

Not bad for a 12 hours fix.

**Comment by opusforlife2** [comment]
Awesome! That was fast.
